
spring:
  application:
    name: optimacv-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/optimacv
    username: postgres
    password: ashraf2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    google:
      genai:
        api-key: AIzaSyBES8EPBKUqvMutrDENE8MbrNnEe4p01Sc
        chat:
          options:
            model: models/gemini-2.5-flash
server:
  port: 8080

jwt:
  secret: OptimaCV-S3cur3-JWT-Sign1ng-K3y!
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger
